### ISSUE TITLE
GPU resetting after restart

### ISSUE THREAD

**Issue by clover1980** [risiIndustries/risiOS-meta#5]
I want to report a bug when already installed GPU Nvidia driver resetting to software rendering after reboot.
First time after the reboot GPU reset the full reinstalling of Nvidia 535 driver helped, but second time GPU reset after turning off and turn on computer even reinstalling not helped and after reboot software rendering keep present, which very slow. System was working 24 hours without stop. It’s the only bug I’ve found during hard testing with LLMs, PS3 emulator, 4K Youtube watch (which here is OK, on other distros usually problematic).

Anyway, Risi is a great distro, maybe only one based on Fedora 38 which was fast on always on 4K resolution big TV (3840x2160), my tests with default Fedora, Nobara and Ultramarine 38s show serious slowness in 4K resolution(i believe it’s the reason of sluggishness), which uncomfortable to work.
Great python support also in Risi, but Linux today require comprehensive GPU support, without GPU work with modern Ai impossible.
My hardware Intel Xeon 14 cores, 128Gb RAM, RTX 2070 Super, 4K TV. **Used latest risiOS 38 (20230610)**
P.S.: Also it would be great to have more choice in Display Zoom scale, in Ubuntu there’s a 125% available, but on all Fedora distros next from 100 is only 200% which even on very big TV looking sometimes too large.

**Comment by PizzaLovingNerd** [comment]
Are you installing manually or with risiWelcome?

**Comment by clover1980** [comment]
> Are you installing manually or with risiWelcome?

i don't like to compile anything, so drivers was installed and removed only through default app store application.

**Comment by PizzaLovingNerd** [comment]
that was the issue. They should have been installed in risiWelcome.

Here is the script copy and pasted from risiWelcome's code. (make sure to run as root/sudo). Make sure to remove them again from the software center first.

```echo Installing RPMFusion Repositories
dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
echo Updating AppStream
dnf groupupdate core -y --skip-broken
echo Installing Multimedia Packages
dnf swap -y ffmpeg-free ffmpeg --allowerasing
dnf groupupdate multimedia -y --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin --skip-broken
echo Sound and Video Packages
dnf groupupdate sound-and-video -y --skip-broken
dnf install -y akmod-nvidia xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs nvidia-vaapi-driver```
